apiVersion: v1
kind: Secret
metadata:
  name: web-codex-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: "sk-..."
  GH_TOKEN: "ghp-..."
  GH_USER: "your-gh-username"
  GH_ORGS: "org1,org2"
  GL_TOKEN: "glpat-..."
  GL_BASE_URL: "https://gitlab.com"
  GL_GROUPS: "12345,group/subgroup"
